### ISSUE TITLE
Unused parameter 'unbind(std::string& s)' line 397

### ISSUE THREAD

**Issue by GeorgeDuckman** [adeharo9/cpp-dotenv#13]
The use of the library on a project using the compilation option "-Wunused-parameter" shows that the function "**inline void unbind(std::string& s)**" line 397 does not use its parameter.

I use the library with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html).

A solution would be to set the library's compilation options in its CMakeLists.txt with [target_compile_options](https://cmake.org/cmake/help/latest/command/target_compile_options.html) or removing the parameter name in the code like this :

```c++
        inline void unbind(std::string& /*s*/)
        {
            binded = nullptr;
            bond = false;
        }
```

Do you have any other solutions?

**Comment by adeharo9** [comment]
Absolutely right. I guess at some point during the initial development I simply removed its usage from the `unbind` function but failed to delete the parameter and update the rest of the code.

I'll simply remove it and add the change for the next update on master.

**Comment by adeharo9** [comment]
Solved and merged to `dev`.

Merging to master is still pending, but will happen in the upcoming days with several more changes and updates than I'm introducing.

Closing the issue for now.
