### ISSUE TITLE
Able to read .env links

### ISSUE THREAD

**Issue by Vi1i** [adeharo9/cpp-dotenv#2]
I was trying to do a quick test and used a soft link in Linux (`ln -s`) and received:
```
./read 
terminate called after throwing an instance of 'dotenv::syntax_error'
  what():  Syntax error on line 15:29
Aborted (core dumped)
```
If I do a direct copy instead, no errors. I have verified that I did a correct link.

Interestingly my file is 15 lines long.

**Comment by Vi1i** [comment]
Hmm It might not be an issue with the link. I think that perhaps having a environment variable that has spaces in it might be the cause. Commenting out the below line fixed the issue. Also, changing the spaces to anything else removes the error. This is not how python-dotenv works, so I am unsure if the grammar is wrong here or the grammar is wrong there.

`L4_4SQ_FILE_FILTER="Chicago LosAngeles NewYork"`

**Comment by adeharo9** [comment]
There were some issues while parsing strings (described on #5 ) that should already be fixed with the last commmits on `dev` branch. Going to do some tests, add a few more bug corrections and push it all to master.
